### ISSUE TITLE
Recv failure: Connection reset by peer (Valhalla)

### ISSUE THREAD

**Issue by danirisdiandita** [gis-ops/docker-valhalla#8] opened 2020-09-08 13:50 UTC
I try to build valhalla docker via https://hub.docker.com/r/gisops/valhalla  and following tutorial from 

https://gis-ops.com/valhalla-how-to-run-with-docker-on-ubuntu-18-04/

by using 

`docker run -dt --name valhalla_gis-ops -p 8002:8002 -v $PWD/custom_files:/custom_files gisops/valhalla:3.0.9`

then I downloaded a `pbf` file and dump them into `/custom_files`. 

```
mkdir custom_files
cd custom_files
wget https://download.geofabrik.de/europe/albania-latest.osm.pbf
```

and applying `docker restart`. 

I try to POST the API by sending 

```
curl http://localhost:8002/route \
--data '{"locations":[
              {"lat":41.318818,"lon":19.461336},
              {"lat":41.321001,"lon":19.459598}
           ],
         "costing":"auto",
         "directions_options":{"units":"miles"}
        }' | jq '.'

```

however I got error below

`curl: (56) Recv failure: Connection reset by peer` 

I have been long enough tuning valhalla and following tutorials but it seems it never works as expected.

**Comment by TimMcCauley** [comment] 2020-09-11 05:39
Hi @danirisdiandita, are you certain it is running on port 8002 and is not terminated after the docker run process has finished? Can you post the last 200 lines of logs of the container?

**Comment by nilsnolde** [comment] 2020-10-02 09:10
closing.. feel free to open with more details if it's not solved yet.

**Closed by nilsnolde** 2020-10-02 09:10 UTC

**Comment by message** [comment] 2021-06-26 13:01
I have the same issue. What am doing wrong? [Docker log](https://pastebin.com/bZZzw56f).

Request was terminated in 30 seconds.
```
root@machine:/home/message# curl http://localhost:8002/route --data '{"locations":[{"lat":41.318818,"lon":19.461336},{"lat":41.321001,"lon":19.459598}],"costing":"auto","directions_options":{"units":"miles"}}' | jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   139    0     0  100   139      0      4  0:00:34  0:00:31  0:00:03     0
curl: (56) Recv failure: Connection reset by peer
```

**Comment by nilsnolde** [comment] 2021-06-26 13:11
don't see anything wrong in the graph build logs.. can you show the output of `docker ps`? 

didn't test now and not sure how much magic is going in curl, but I usually use `curl -XPOST 'http://localhost:8002/route' -H'Content-Type: application/json'` on top of the params.

**Comment by message** [comment] 2021-06-26 13:19
I'm testing also OSRM

`docker ps` output:
```
root@machine:/home/message# docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
6d83ab60353a   gisops/valhalla:latest               "/bin/sh -c /valhall…"   28 minutes ago   Up 9 minutes              0.0.0.0:8002->8002/tcp, :::8002->8002/tcp   gisops_docker_valhalla_1
76b7500172c2   vroomvrp/vroom-docker:v1.10.0        "/bin/bash /docker-e…"   36 hours ago     Up 36 hours (unhealthy)                                               festive_robinson
74d0b9fa2935   osrm/osrm-backend                    "osrm-routed --algor…"   36 hours ago     Up 36 hours               0.0.0.0:5000->5000/tcp, :::5000->5000/tcp   strange_germain
e20a3c529331   aerospike/aerospike-server:5.5.0.3   "/usr/bin/dumb-init …"   2 months ago     Up 37 hours               127.0.0.1:3000-3003->3000-3003/tcp          aerospike_aerospike_1
```

Second docker launch: https://pastebin.com/ZeXzFn2d

Output of a CURL is the same event with POST.
```
root@machine:/home/message# curl -X POST 'http://localhost:8002/route' -H 'Content-Type: application/json' --data '{"locations":[{"lat":41.318818,"lon":19.461336},{"lat":41.321001,"lon":19.459598}],"costing":"auto","directions_options":{"units":"miles"}}' | jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   139    0     0  100   139      0      4  0:00:34  0:00:31  0:00:03     0
curl: (56) Recv failure: Connection reset by peer
```

**Comment by message** [comment] 2021-06-26 16:26
To be fair, I just restarted osrm docker container, and while it was not ready, i received same curl error. We need to find out what is the cause of valhalla docker image not responding.

**Comment by nilsnolde** [comment] 2021-06-26 17:29
let me try to reproduce one of these days. one more thing: you're docker-compose seems a bit older. I recently refactored quite a bit, specifically the `force_*` are gone. I don't think it'll change anything for you though, more of a comment.

and one more thing you can try: if you `exec` into the container and do the same curl, what happens? and while you're inside the container, you can try a `valhalla_service --config /custom_files/valhalla.json 2` and then try curl again from the host.

now that I see `vroom` there: probably you're aware of that, but valhalla's matrix api is pretty slow, so if you need to optimize > few hundred locations, you'll need patience;)

**Comment by message** [comment] 2021-06-27 19:21
What are those two warns in the end? 
```
root@machine:/home/message/valhalla# docker-compose up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Starting valhalla_valhalla_1 ... done
Attaching to valhalla_valhalla_1
valhalla_1  | Valid valhalla_tiles.tar found with use_tiles_ignore_pbf: True!
valhalla_1  | Jumping directly to the tile loading!
valhalla_1  | 
valhalla_1  | ==========================
valhalla_1  | = Using existing config file =
valhalla_1  | ==========================
valhalla_1  | 
valhalla_1  | ==========================
valhalla_1  | = Skipping admin regions =
valhalla_1  | ==========================
valhalla_1  | ==========================
valhalla_1  | 
valhalla_1  | ===========================
valhalla_1  | = Download the elevation tiles =
valhalla_1  | ===========================
valhalla_1  | extracting 20 elevation tiles
valhalla_1  | 
valhalla_1  | Computers / CPU cores / Max jobs to run
valhalla_1  | 1:local / 64 / 1
0alhalla_1  | 
valhalla_1  | checking all files exist
valhalla_1  | checking file sizes
valhalla_1  | Found config file. Starting valhalla service!
valhalla_1  | 2021/06/27 19:10:47.828974 [INFO] Tile extract successfully loaded with tile count: 231
valhalla_1  | 2021/06/27 19:10:47.829217 [WARN] (stat):  No such file or directory
valhalla_1  | 2021/06/27 19:10:47.829229 [WARN] Traffic tile extract could not be loaded
```

That's my [/custom_files/valhalla.json](https://pastebin.com/gM4w49Ni) 

By `exec`ing into a container, i get same result.

```
root@dc6d6984efc5:/# valhalla_service --config /custom_files/valhalla.json 2
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open file --config
Aborted (core dumped)
root@dc6d6984efc5:/# valhalla_service /custom_files/valhalla.json 2
terminate called after throwing an instance of 'std::runtime_error'
  what():  Address already in use
Aborted (core dumped)
root@dc6d6984efc5:/# valhalla_service /custom_files/valhalla-custom-port.json 2
2021/06/27 19:20:43.962576 [INFO] Tile extract successfully loaded with tile count: 231
2021/06/27 19:20:43.962804 [WARN] (stat):  No such file or directory
2021/06/27 19:20:43.962817 [WARN] Traffic tile extract could not be loaded
^C
root@dc6d6984efc5:/# 
```

**Comment by message** [comment] 2021-06-27 19:24
Yeap, making CURL requests from inside of container - works!

```
root@machine:/home/message/valhalla/custom_files# docker exec -it dc6d6984efc5 bash 

root@dc6d6984efc5:/# curl http://localhost:8002/route --data '{"locations":[{"lat":41.318818,"lon":19.461336},{"lat":41.321001,"lon":19.459598}],"costing":"auto","directions_options":{"units":"miles"}}'
{"trip":{"locations":[{"type":"break","lat":41.318818,"lon":19.461336,"original_index":0},{"type":"break","lat":41.321001,"lon":19.459598,"original_index":1}],"legs":[{"maneuvers":[{"type":1,"instruction":"Drive northwest on Rruga Stefan Kaçulini.","verbal_pre_transition_instruction":"Drive northwest on Rruga Stefan Kaçulini. Then, in 900 feet, You will arrive at your destination.","verbal_post_transition_instruction":"Continue for 900 feet.","street_names":["Rruga Stefan Kaçulini"],"time":21.151,"length":0.178,"cost":41.314,"begin_shape_index":0,"end_shape_index":7,"verbal_multi_cue":true,"travel_mode":"drive","travel_type":"car"},{"type":4,"instruction":"You have arrived at your destination.","verbal_transition_alert_instruction":"You will arrive at your destination.","verbal_pre_transition_instruction":"You have arrived at your destination.","time":0.0,"length":0.0,"cost":0.0,"begin_shape_index":7,"end_shape_index":7,"travel_mode":"drive","travel_type":"car"}],"summary":{"has_time_restrictions":false,"min_lat":41.318814,"min_lon":19.459558,"max_lat":41.321021,"max_lon":19.461327,"time":21.151,"length":0.178,"cost":41.314},"shape":"{x{xmA_lybd@aExCuVxQuWdScSdPmSjOuVxPgRlN"}],"summary":{"has_time_restrictions":false,"min_lat":41.318814,"min_lon":19.459558,"max_lat":41.321021,"max_lon":19.461327,"time":21.151,"length":0.178,"cost":41.314},"status_message":"Found route between points","status":0,"units":"miles","language":"en-US"}}

root@dc6d6984efc5:/# valhalla_service --config /custom_files/valhalla.json 2
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open file --config
Aborted (core dumped)
root@dc6d6984efc5:/# valhalla_service /custom_files/valhalla.json 2
terminate called after throwing an instance of 'std::runtime_error'
  what():  Address already in use
Aborted (core dumped)
root@dc6d6984efc5:/# valhalla_service /custom_files/valhalla-custom-port.json 2
2021/06/27 19:20:43.962576 [INFO] Tile extract successfully loaded with tile count: 231
2021/06/27 19:20:43.962804 [WARN] (stat):  No such file or directory
2021/06/27 19:20:43.962817 [WARN] Traffic tile extract could not be loaded
^C
```

**Comment by nilsnolde** [comment] 2021-06-28 07:35
Seems like an issue in your docker setup. I can't reproduce, for me it works from the host as well. Weird though if OSRM should work, but Valhalla not.. it's at least not a problem with this project.

docker-compose
```
version: '3.0'
services:
  valhalla:
    image: gisops/valhalla:latest
    container_name: valhalla_temp
    #build:
    #  context: .
    #  args:
    #    - VALHALLA_RELEASE=nn_python_install_fix
    #    - PRIMESERVER_RELEASE=0.6.5
    ports:
      - 8002:8002
    volumes:
      - ./custom_files/:/custom_files
    environment:
      # Auto-download PBFs from Geofabrik
      - tile_urls=https://download.geofabrik.de/europe/andorra-latest.osm.pbf https://download.geofabrik.de/europe/albania-latest.osm.pbf
      # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
      - server_threads=2  # determines how many threads will be used to run valhalla
      - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
      - build_elevation=False  # build elevation with "True" or "Force", needs valid coordinates min_x, min_y etc
      - build_admins=False  # build admins db with "True" or "Force"
      - build_time_zones=False  # build timezone db with "True" or "Force"
      - force_rebuild=False  # forces a rebuild of the routing tiles with "True"
```

**Comment by message** [comment] 2021-07-03 14:07
Hey Nils, sorry for an off-topic, but I need to find the best route between 250 points. Starting from Riga. I already made made this calculation with OSRM + vroom, but it made some questionable decisions, so I want to give Valhalla a try.

![Screenshot from 2021-07-03 17-04-40](https://user-images.githubusercontent.com/492026/124356822-e260f000-dc20-11eb-912d-10747d14e0b7.png)

I'm still launching this query within a container. Couldn't make my firewall work.  

I've got this issue with 24 locations :) Can you hook me up with best `valhalla.json` for this task? 

```
reset && curl http://localhost:8002/optimized_route --data '{"locations":[{"lat":47.1267383, "lon":10.9491681},{"lat":46.9769744, "lon":11.1096957},{"lat":46.6704304, "lon":11.1629543},{"lat":46.738261, "lon":10.834322},{"lat":46.8107149, "lon":10.5365807},{"lat":46.6808166, "lon":9.6762957},{"lat":46.6756358, "lon":9.6711998},{"lat":46.812695, "lon":9.3197939},{"lat":46.8255802, "lon":9.2905816},{"lat":47.139588, "lon":9.5243035},{"lat":47.2834461, "lon":9.4145734},{"lat":47.3285877, "lon":9.4094809},{"lat":47.6781269, "lon":8.6149573},{"lat":47.3650667, "lon":8.5463022},{"lat":47.052873, "lon":8.336391},{"lat":46.9794705, "lon":8.2548011},{"lat":46.6863481, "lon":7.8632049},{"lat":46.5896318, "lon":7.9052932},{"lat":46.5616551, "lon":7.8585084},{"lat":46.564167, "lon":7.887778},{"lat":46.5693, "lon":7.9145},{"lat":46.6054335, "lon":7.9215399}],"costing":"auto","directions_options":{"units":"kilometers"}}' | jq '.'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   951    0    92  100   859      0      4  0:03:34  0:02:59  0:00:35    24
{
  "error_code": 499,
  "error": "Unknown:std::bad_alloc",
  "status_code": 400,
  "status": "Bad Request"
}
```

**Comment by nilsnolde** [comment] 2021-07-03 18:50
That’s not a config issue, that’s a bug IMO. I got no experience with the TSP endpoint, so not sure what the problem is.. You might have to file a bug report at Valhalla’s repository.
